name: 'Sphinx Build (composite)'
description: 'Builds documentation using Sphinx'
author: 'Ammar Askar'
branding:
  icon: 'book'
  color: 'yellow'
inputs:
  docs-folder:
    description:
      The folder containing your sphinx docs.
    required: true
    default: "docs/"
  build-command:
    description:
      The command used to build your documentation.
    required: false
    default: make html
runs:
  using: "composite"
  steps:
    - name: Build sphinx documentation
      run: python ${{ github.action_path }}/entrypoint.py
      shell: bash
      env:
        INPUT_DOCS-FOLDER: ${{ inputs.docs-folder }}
        INPUT_BUILD-COMMAND: ${{ inputs.build-command }}
